### ISSUE TITLE
Multiple Buttons are Mixed

### ISSUE THREAD

**Issue by KronKraken-zz** [wyozi/3d2d-imgui#1]
So i am using a button on a entity and when i have 2 entities the buttons mix themselves, so 1 controls 2 and 2 controls 1. If that could be fixed i would really apreciate! Thanks!

**Comment by wyozi** [comment]
I can't seem to reproduce. Can you post the code you're using. Here's the code I tested with

``` lua
ENT.Type = "anim"
function ENT:Initialize()
    if SERVER then
        self:PhysicsInit(SOLID_VPHYSICS)
        self:SetMoveType(MOVETYPE_VPHYSICS)
        self:SetSolid(SOLID_VPHYSICS)
        self:SetModel("models/props_borealis/bluebarrel001.mdl")
    end
end

function ENT:Draw()
    self:DrawModel()

    self.p = self.p or tdui.Create()

    if self.p:Button("Woop", "DermaLarge", 0, 0, 100, 50) then
        self:SetColor(Color(math.random(0, 255), math.random(0, 255), math.random(0, 255))) 
    end
    self.p:Render(self:GetPos() + self:GetForward() * -25, self:GetAngles(), 0.1)
end
```

**Comment by KronKraken-zz** [comment]
A sec i'll make you a video

**Comment by KronKraken-zz** [comment]
But wait is that rendering server side? I am rendering client side, any problems with that?

**Comment by wyozi** [comment]
It is rendering on clientside. It is a shared file. I spawned two barrels and the button on each of them works independently of each other.

If I had to guess, I'd say you're maybe not caching the tdui panel properly. Make sure you don't store it in a local variable but the `self` object.

**Comment by KronKraken-zz** [comment]
http://i.imgur.com/N1uYn4O.jpg = 1 Printer Works fine
http://i.imgur.com/niuF8fX.jpg = 2 Printers, struggle(sorry for bug on the print)

**Comment by wyozi** [comment]
I just tested two independently working entities, so I'm not sure if it's my code not working. Are you sure you don't for example store the printer status in `ENT` instead of `self`` or use the same tdui panel for two entities?

I don't think I can help you further without seeing the code you're using.

**Comment by KronKraken-zz** [comment]
Oh that you said was the actual problem, it was storing it on local p, now it is self.p, so no bug, thanks for the help tho! :D

**Comment by KronKraken-zz** [comment]
The thing was on the readme i saw "local p" so that's why i did it, thanks for the help :+1:

**Comment by wyozi** [comment]
Yeah, I'll try to clarify it a bit. Maybe a PostDrawTranslucentRenderables hook isn't the best example, because most people want to use it for entities :octocat:
