### ISSUE TITLE
Does this not work anymore?

### ISSUE THREAD

**Issue by camerons343** [wyozi/3d2d-imgui#14]
I'm doing it how I'm supposed to do and nothing happens but errors and every time its telling me

[ERROR] CG] Chikkenslayer:12: attempt to index upvalue 'tdui' (a nil value)
1. fn - [STEAM_0:1:40778419][CG] Chikkenslayer:12
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

**Comment by wyozi** [comment]
Make sure you do exactly as the current setup instructions say. If it still
doesn't work, post your code.
