### ISSUE TITLE
Running serverside code in a button

### ISSUE THREAD

**Issue by Zer0nix** [wyozi/3d2d-imgui#19]
I want to make the button give the player ammo, or a weapon, I'm currently running the script in shared.lua and I tried making the button part serverside but it still doesn't work. No errors, but nothing happens when I press the button. ( The RunConsoleCommand works just fine tho). Sorry for bothering again but I've actually tried everything I could think of.

```
self.p = self.p or tdui.Create()
    
    local p = self.p
    local ply = LocalPlayer()

    -- Draw a button (text, font, x, y, w, h, [color])
    if p:Button("$500", "AmmoM", 65,9, 50, 50) then

      
if SERVER then

	ply:Give("weapon_smg1")
end         
          
    end
    p:Cursor()
    p:Render(posss + offset3, angss, 0.15)
    
end

```

**Comment by wyozi** [comment]
Use net messages.
