### ISSUE TITLE
Buttons not registering?

### ISSUE THREAD

**Issue by KronKraken-zz** [wyozi/3d2d-imgui#3]
Thanks for the update but i think you've just created a new bug. Sometimes the buttons just dont work D: Helep ples

**Comment by wyozi** [comment]
I think it's because of the behind panel check. Try this version https://github.com/wyozi/3d2d-imgui/blob/3e0d4488d40265b38f974a5a1cb2f5f610c35a44/lua/autorun/client/3d2dimgui.lua and let me know if the problem still happens.

**Comment by KronKraken-zz** [comment]
Okay a sec

**Comment by KronKraken-zz** [comment]
Nope, nothing, still broken

**Comment by wyozi** [comment]
It means the trace is hitting something probably invisible or a hat or something like that.

Add `print(tr.Entity)` here https://github.com/wyozi/3d2d-imgui/blob/master/lua/autorun/client/3d2dimgui.lua#L375 and let me know what the console is printing when you're unable to press a button.

**Comment by KronKraken-zz** [comment]
Entity [103] [kp_basic_printer]

My Entity

**Comment by wyozi** [comment]
You can probably fix that by moving the TDUI be further away from the printer. I'm not sure how should I fix this in code. If it's still a problem I can figure out something, but you should probably try that first.

**Comment by KronKraken-zz** [comment]
Kay thanks mate!
